# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.2"
manifest_format = "2.0"
project_hash = "ad85503118162e08bb93dfc72059174673e8772b"

[[deps.EfficientNetSeq2label]]
path = "."
uuid = "356fff74-3787-4fec-bfc9-b8569907faee"
version = "1.0.0-DEV"
