name = "EfficientNetSeq2label"
uuid = "356fff74-3787-4fec-bfc9-b8569907faee"
authors = ["Shane Kuei-Hsien Chu (skchu@wustl.edu)"]
version = "1.0.0-DEV"

[compat]
julia = "1.12.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
